#!/usr/bin/env python2
# -*- coding: utf8 -*-
# Author: pidpawel <pidpawel.eu>
# Author: aysorth
# Webpage: https://github.com/pidpawel/dnsreport/
# License: http://creativecommons.org/licenses/by-sa/3.0/

from dns import resolver, reversename
import argparse
import re

parser = argparse.ArgumentParser(description='Query DNS for extra data')
parser.add_argument('--no-color', dest='color', action='store_false', help='Prevent from using colors')
parser.add_argument('target', nargs='+', help='Targets to scan')
parser.add_argument('-n', dest='ns', help='Nameserver to query')

args = parser.parse_args()

if args.color:
    RED = '\033[31m'
    GREEN = '\033[32m'
    BLUE = '\033[34m'
    YELLOW = '\033[33m'
    END = '\033[0m'
else:
    RED = ''
    GREEN = ''
    BLUE = ''
    YELLOW = ''
    END = ''

if args.ns:
    resolver = resolver.Resolver(configure=False)
    resolver.nameservers = [args.ns]
    nameserver = args.ns
else:
    nameserver = 'default'  # TODO: figure out how to get default
                            # ns from dnspython, if possible

# This lib does not allow ANY requests, so…
standard_record_types = (
    'SOA', 'A', 'AAAA', 'MX', 'SRV', 'TXT', 'DNAME', 'NS', 'SPF', 'PTR', 'RP', 'CNAME'
#'AFSDB', 'APL', 'CERT', 'DHCID', 'DLV', 'DNAME', 'DNSKEY', 'DS', 'HIP',
#'IPSECKEY', 'KEY', 'KX', 'LOC', 'NAPTR', 'NSEC', 'NSEC3', 'NSEC3PARAM',
#'PRSIG', 'SIG', 'SSHFP', 'TA', 'TLSA', 'TSIG', 'AXFR', 'IXFR', 'OPT'
)


def make_report(domain):
    print(RED + domain + END + " using nameserver " + BLUE + nameserver + END)

    for record_type in standard_record_types:
        root_last = (record_type == standard_record_types[-1])

        try:
            answer = resolver.query(domain, record_type)
        except:
            if root_last:
                print('╰─ ' + YELLOW + record_type + END)
            else:
                print('├─ ' + YELLOW + record_type + END)
        else:
            if root_last:
                print('╰─ ' + GREEN + record_type + END)
            else:
                print('├─ ' + GREEN + record_type + END)
            for index, line in enumerate(answer):
                line_s = str(line)
                line_last = (index == len(answer) - 1)

                rl = ' ' if root_last else '│'
                ll = ' ' if line_last else '│'
                llt = '╰' if line_last else '├'

                print(rl + '  ' + llt + '─' + BLUE + line_s + END)

                if record_type in ('A', 'AAAA'):
                    try:
                        rev = revdns(line_s, in_make_report=True)
                    except:
                        pass
                    else:
                        try:
                            if rev == domain:
                                print('├─────┴ ' + RED + rev + END)
                            else:
                                print(rl + '  ' + ll + ' ╰─' + RED + rev + END)
                        except:
                            pass


def revdns(ip, in_make_report=False):
    try:
        in_addr = reversename.from_address(ip)
        rev = str(resolver.query(in_addr, 'PTR')[0])
        if in_make_report is not True:
            print(RED + ip + END)
            print('╰─ ' + GREEN + rev + END)
        else:
            return rev
    except:
        if in_make_report is not True:
            print("RevDNS for " + RED + ip + END + " could not be found.")


def is_ip(target):
    ipv4pattern = "((2[0-5]{2}|2[0-4]\d|1\d{2}|[1-9]\d|\d)\.){3}(2[0-5]{2}|2[0-4]\d|1\d{2}|[1-9]\d|\d)(/(3[012]|[12]\d|\d))?"
    v4 = re.compile(ipv4pattern)
    if v4.match(target):
        return True

    ipv6pattern = "^((([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(([0-9A-Fa-f]{1,4}:){0,5}:((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(::([0-9A-Fa-f]{1,4}:){0,5}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:))$"
    v6 = re.compile(ipv6pattern)
    if v6.match(target) is not None:
        return True

    return False


def is_domain(target):
    domain_pattern = "^[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,4}$"
    dom = re.compile(domain_pattern)
    if dom.match(target):
        return True
    return False


for t in args.target:
    if is_ip(t):
        revdns(t)
    elif is_domain(t):
        make_report(t)
    else:
        parser.print_help()
        print("\nTarget has to be either a valid IP address or a domain.")
